version: '3'

services:
  mini-pin:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
    restart: unless-stopped